export interface SendOtpDto {
  to: string;
  otp?: string;
  appName?: string;
  expiresInMinutes?: number;
  message?: string;
  webhookUrl?: string;
  bypassRateLimit?: boolean;
}

export interface SendOtpResult {
  messageId: string;
  recipient: string;
  maskedRecipient: string;
  otp: string;
  isAutoGenerated?: boolean;
  appName: string;
  sentAt: string;
  latencyMs: number;
  simulatedTypingMs?: number;
  verificationExpiryMinutes?: number;
}

export interface VerifyOtpDto {
  to: string;
  otp: string;
}

export interface VerifyOtpResult {
  success: boolean;
  verified: boolean;
  message: string;
  attemptsRemaining?: number;
  appName?: string;
}
