import { AppConfig } from '../../../core/config/app.config.js';
import { ErrorCodes } from '../../../core/errors/error-codes.js';
import { ServiceUnavailableError, ValidationError } from '../../../core/errors/app-error.js';
import { eventBus } from '../../../core/events/event-bus.js';
import { whatsAppService } from '../../whatsapp/application/whatsapp.service.js';
import { PhoneFormatter } from '../domain/phone-formatter.js';
import { otpRateLimiter } from '../domain/rate-limiter.js';
import { otpVerificationStore } from '../domain/otp-verification.store.js';
import { webhookDispatcher } from '../infrastructure/webhook-dispatcher.js';
import { MessageTemplateEngine } from '../domain/message-template.js';
import { SendOtpDto, SendOtpResult, VerifyOtpDto, VerifyOtpResult } from '../domain/otp.types.js';

export class OtpService {
  public async sendOtp(
    dto: SendOtpDto,
    developerId: string = 'dev_system',
    developerName?: string
  ): Promise<SendOtpResult> {
    const startTime = Date.now();
    const waState = whatsAppService.getState();
    const sock = whatsAppService.getActiveSocket();

    if (waState.status !== 'connected' || !sock) {
      throw new ServiceUnavailableError(
        'Gagal mengirim OTP: WhatsApp belum terhubung. Buka dasbor dan scan QR Code WhatsApp menggunakan menu "Perangkat Tertaut" pada aplikasi WhatsApp ponsel Anda.',
        ErrorCodes.WA_NOT_CONNECTED
      );
    }

    // 1. Determine OTP (Auto-generate random 6-digit code if omitted or empty)
    let isAutoGenerated = false;
    let trimmedOtp = dto.otp?.trim() || '';
    if (!trimmedOtp) {
      trimmedOtp = Math.floor(100000 + Math.random() * 900000).toString();
      isAutoGenerated = true;
    }

    // 2. Normalize & Validate Phone Number
    const cleanNumber = PhoneFormatter.validate(dto.to);
    const maskedPhone = PhoneFormatter.mask(cleanNumber);
    const jid = PhoneFormatter.toJid(cleanNumber);

    // 3. Priority 1: Enforce Rate Limiter & Cooldown
    otpRateLimiter.checkAndRecord(cleanNumber, developerId, dto.bypassRateLimit);

    const appName = dto.appName || AppConfig.otp.defaultAppName;
    const expiresIn = dto.expiresInMinutes || AppConfig.otp.defaultExpiresInMinutes;

    // 4. Priority 2: Construct & Compile WhatsApp Message Template with Placeholders
    const messageText = MessageTemplateEngine.compile(dto.message || '', {
      otp: trimmedOtp,
      appName,
      expiresInMinutes: expiresIn,
      phone: '+' + cleanNumber,
    });

    const logId = 'otp_' + Math.random().toString(36).substring(2, 9);
    const sentAt = new Date().toISOString();

    // Record initial pending log
    eventBus.emit('delivery:created', {
      id: logId,
      recipient: '+' + cleanNumber,
      maskedRecipient: '+' + maskedPhone,
      otp: trimmedOtp,
      appName,
      status: 'pending',
      sentAt,
      latencyMs: 0,
      developerId,
      developerName,
    });

    eventBus.emit('console:log', {
      level: 'info',
      source: 'hono-api',
      message: `Mempersiapkan pengiriman OTP ke +${maskedPhone} (Aplikasi: ${appName})...`,
    });

    // 4. Priority 1: Human-Like Presence Simulation (Typing Delay)
    let typingDelayMs = 0;
    if (AppConfig.simulation.typingPresence) {
      typingDelayMs = Math.floor(
        AppConfig.simulation.minTypingDelayMs +
          Math.random() * (AppConfig.simulation.maxTypingDelayMs - AppConfig.simulation.minTypingDelayMs)
      );

      try {
        await sock.sendPresenceUpdate('composing', jid);
        await new Promise((resolve) => setTimeout(resolve, typingDelayMs));
        await sock.sendPresenceUpdate('paused', jid);
      } catch {
        // Fallback gracefully if presence update fails
      }
    }

    try {
      const result = await sock.sendMessage(jid, { text: messageText });
      const latencyMs = Date.now() - startTime;
      const messageId = result?.key?.id || 'wa_' + Date.now();

      // 5. Priority 2: Save active OTP session for optional verification
      otpVerificationStore.saveSession(cleanNumber, trimmedOtp, appName, expiresIn);

      // 6. Priority 2: Register Webhook if provided
      if (dto.webhookUrl) {
        webhookDispatcher.registerMessageWebhook(messageId, dto.webhookUrl);
        // Trigger initial sent webhook
        webhookDispatcher.dispatch(dto.webhookUrl, {
          event: 'otp.sent',
          timestamp: new Date().toISOString(),
          data: {
            messageId,
            recipient: '+' + cleanNumber,
            maskedRecipient: '+' + maskedPhone,
            status: 'sent',
            appName,
            latencyMs,
          },
        }).catch(() => {});
      }

      // Emit delivery success
      eventBus.emit('delivery:updated', {
        id: logId,
        status: 'sent',
        messageId,
        latencyMs,
      });

      eventBus.emit('console:log', {
        level: 'success',
        source: 'whatsapp',
        message: `OTP berhasil dikirim ke +${maskedPhone} (ID: ${messageId}, Latensi total: ${latencyMs}ms, Typing: ${typingDelayMs}ms)`,
      });

      return {
        messageId,
        recipient: '+' + cleanNumber,
        maskedRecipient: '+' + maskedPhone,
        otp: trimmedOtp,
        isAutoGenerated,
        appName,
        sentAt,
        latencyMs,
        simulatedTypingMs: typingDelayMs,
        verificationExpiryMinutes: expiresIn,
      };
    } catch (sendErr: any) {
      const latencyMs = Date.now() - startTime;

      eventBus.emit('delivery:updated', {
        id: logId,
        status: 'failed',
        latencyMs,
        errorMessage: sendErr?.message || 'Gagal mengirim pesan',
      });

      eventBus.emit('error:logged', {
        category: 'delivery',
        code: ErrorCodes.WA_SEND_FAILED,
        title: `Gagal mengirim pesan OTP ke +${cleanNumber}`,
        details: { error: sendErr?.message, jid },
        suggestedAction:
          'Pastikan nomor penerima terdaftar di WhatsApp dan ponsel server memiliki koneksi internet aktif.',
      });

      if (dto.webhookUrl) {
        webhookDispatcher.dispatch(dto.webhookUrl, {
          event: 'otp.failed',
          timestamp: new Date().toISOString(),
          data: {
            recipient: '+' + cleanNumber,
            maskedRecipient: '+' + maskedPhone,
            status: 'failed',
            appName,
            error: sendErr?.message,
          },
        }).catch(() => {});
      }

      throw new ServiceUnavailableError(
        `Pengiriman WhatsApp gagal: ${sendErr?.message || 'Koneksi error'}`,
        ErrorCodes.WA_SEND_FAILED
      );
    }
  }

  /**
   * Verify an active OTP code for a recipient phone number
   */
  public verifyOtp(dto: VerifyOtpDto): VerifyOtpResult {
    if (!dto.to || !dto.otp) {
      throw new ValidationError("Parameter 'to' dan 'otp' wajib diisi untuk verifikasi.");
    }

    const cleanNumber = PhoneFormatter.validate(dto.to);
    const result = otpVerificationStore.verify(cleanNumber, dto.otp);

    eventBus.emit('console:log', {
      level: result.verified ? 'success' : 'warn',
      source: 'hono-api',
      message: `Hasil verifikasi OTP (+${PhoneFormatter.mask(cleanNumber)}): ${result.verified ? 'VALID' : 'INVALID'}`,
    });

    return result;
  }
}

export const otpService = new OtpService();
