export const ErrorCodes = {
  // Auth Errors
  AUTH_HEADER_MISSING: 'AUTH_HEADER_MISSING',
  AUTH_FORMAT_INVALID: 'AUTH_FORMAT_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN_PERMISSION: 'AUTH_FORBIDDEN_PERMISSION',

  // Rate Limiting & Throttling
  RATE_LIMIT_COOLDOWN: 'RATE_LIMIT_COOLDOWN',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Validation Errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_PHONE_REQUIRED: 'VALIDATION_PHONE_REQUIRED',
  PHONE_INVALID_FORMAT: 'PHONE_INVALID_FORMAT',
  OTP_EMPTY: 'OTP_EMPTY',

  // OTP Verification
  OTP_SESSION_NOT_FOUND: 'OTP_SESSION_NOT_FOUND',
  OTP_SESSION_EXPIRED: 'OTP_SESSION_EXPIRED',
  OTP_CODE_MISMATCH: 'OTP_CODE_MISMATCH',
  OTP_MAX_ATTEMPTS_EXCEEDED: 'OTP_MAX_ATTEMPTS_EXCEEDED',

  // WhatsApp Socket Errors
  WA_NOT_CONNECTED: 'WA_NOT_CONNECTED',
  WA_SEND_FAILED: 'WA_SEND_FAILED',
  SOCKET_INIT_FAILED: 'SOCKET_INIT_FAILED',
  PAIRING_CODE_FAILED: 'PAIRING_CODE_FAILED',
  QR_RENDER_FAILED: 'QR_RENDER_FAILED',

  // Webhook Errors
  WEBHOOK_DISPATCH_FAILED: 'WEBHOOK_DISPATCH_FAILED',

  // System Errors
  SERVER_INTERNAL_ERROR: 'SERVER_INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
